# Generated by Django 3.0.4 on 2020-03-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsite',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='constructionsite',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='material',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='material',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_by',
        ),
    ]
