# Generated by Django 3.0.4 on 2020-03-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_site', '0002_auto_20200304_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ('-delivered_on',)},
        ),
    ]
